name: cicd
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: clone the repository
        uses: actions/checkout@v4.1.2
      - name: setup java version
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build the project
        run: mvn package
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker image build
        run: |
          docker build -t myapp:latest .
          docker images
      - name: Test the image by creating the container
        run: |
          docker run -dt --name web1 myapp:latest
          docker ps -a
      - name: Login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Image to dockerhub
        run: |
          docker tag myapp:latest gagandeepthinknyx/intel1:latest
          docker push gagandeepthinknyx/intel1:latest

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: clone the repository
        uses: actions/checkout@v4.1.2
      - name: Deploy the k8s deployment
        run: |
          sudo kubectl apply -f deployment.yml
          sudo kubectl get pods
